export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_REQUEST_SUCCEEDED = 'ADD_PRODUCT_REQUEST_SUCCEEDED';

export const GET_API_PRODUCTS_REQUEST = 'GET_API_PRODUCTS_REQUEST';
export const GET_API_PRODUCTS_REQUEST_SUCCEEDED = 'GET_API_PRODUCTS_REQUEST_SUCCEEDED';

export const INCREMENT_PRODUCT_REQUEST = 'INCREMENT_PRODUCT_REQUEST';
export const INCREMENT_PRODUCT_REQUEST_SUCCEEDED = 'INCREMENT_PRODUCT_REQUEST_SUCCEEDED';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST_SUCCEEDED = 'DELETE_PRODUCT_REQUEST_SUCCEEDED';

export const REQUEST_FAILURE = 'REQUEST_FAILURE';
